# 打包 Android apk（Windows，实测可用流程）
#
#   .\build-apk.ps1                默认出 arm64 release apk（已签名）
#   .\build-apk.ps1 -Debug         出 debug apk（AGP 自动签名，免手工签名）
#   .\build-apk.ps1 -Abi x86_64    换架构（arm64-v8a / armeabi-v7a / x86 / x86_64）
#
# 为什么要绕开 `cargo tauri android build`：
#   它把编译好的 .so 以**符号链接**放进 jniLibs，而 Windows 建符号链接需要
#   开发者模式或管理员权限，普通环境会直接失败。
#   这里改成：cargo 编好 → 手工 copy 到 jniLibs → 直接跑 gradle（跳过 rust 任务）。

param(
  [switch]$Debug,
  [string]$Abi = "arm64-v8a",
  [string]$GradleBin = "C:\AndroidDL\gradle\gradle-9.6.1\bin\gradle.bat",
  [string]$GradleUserHome = "C:\AndroidDL\gradle-home"
)

$ErrorActionPreference = "Stop"
$root = $PSScriptRoot
$jh = "C:\Program Files\Java\latest\jdk-21"
if (-not (Test-Path $jh)) { throw "找不到 JDK，请修改脚本里的 `$jh" }

$env:JAVA_HOME = $jh
$env:PATH = "$jh\bin;$env:USERPROFILE\.cargo\bin;$env:PATH"
$env:ANDROID_HOME = "C:\Android\sdk"
$env:ANDROID_SDK_ROOT = "C:\Android\sdk"
$env:NDK_HOME = (Get-ChildItem "$env:ANDROID_HOME\ndk" -Directory | Sort-Object Name -Descending | Select-Object -First 1).FullName
$env:GRADLE_USER_HOME = $GradleUserHome

# rust target / jniLibs 目录 / 架构名 / flutter 风格 flavor 名
#
# arch   = gradle 的 rust 插件拼任务名用：rustBuild<Arch 首字母大写><Profile>
# target = 供 -PtargetList 用（tauri 的 rust target 前缀）
# 注意：gen/android/gradle.properties 里 targetList/archList/abiList 默认钉死在 arm64，
# 换 ABI 时**必须**用 -P 覆盖，否则 .so 会被 abiFilters 过滤掉、根本不进包。
$map = @{
  "arm64-v8a"   = @{ triple = "aarch64-linux-android";    arch = "arm64";  target = "aarch64"; flavor = "Universal"; clang = "aarch64-linux-android24-clang.cmd" }
  "armeabi-v7a" = @{ triple = "armv7-linux-androideabi";  arch = "arm";    target = "armv7";   flavor = "Universal"; clang = "armv7a-linux-androideabi24-clang.cmd" }
  "x86"         = @{ triple = "i686-linux-android";       arch = "x86";    target = "i686";    flavor = "Universal"; clang = "i686-linux-android24-clang.cmd" }
  "x86_64"      = @{ triple = "x86_64-linux-android";     arch = "x86_64"; target = "x86_64";  flavor = "Universal"; clang = "x86_64-linux-android24-clang.cmd" }
}
if (-not $map.ContainsKey($Abi)) { throw "不支持的 ABI：$Abi（可选 $($map.Keys -join ', ')）" }
$i = $map[$Abi]

# NDK 链接器必须**显式**给：工程里 .cargo/config.toml 只有镜像源配置，没有 linker。
# 不设这个变量，cargo 会去找系统的 cc → “linker `cc` not found”。
# 变量名规则：CARGO_TARGET_<大写的 triple，横线换下划线>_LINKER
$clang = Join-Path $env:NDK_HOME "toolchains\llvm\prebuilt\windows-x86_64\bin\$($i.clang)"
if (-not (Test-Path $clang)) { throw "找不到 NDK 链接器：$clang（检查 `$env:NDK_HOME）" }
$linkerVar = "CARGO_TARGET_" + ($i.triple.ToUpper() -replace '-', '_') + "_LINKER"
Set-Item -Path "Env:$linkerVar" -Value $clang
Write-Host "   链接器 $linkerVar = $clang" -ForegroundColor DarkGray

Write-Host "1/4 同步前端 ..." -ForegroundColor Cyan
node "$root\tools\sync-frontend.mjs" | Out-Host

Write-Host "2/4 编译 Rust（$($i.triple)）..." -ForegroundColor Cyan
Push-Location "$root\src-tauri"
# --features custom-protocol 必须加：否则 tauri 的 build.rs 会置 dev=true，
# 而移动端 dev=true 时资源不走内嵌、改去反代 dev server → 页面请求 500、App 白屏/黑屏。
cargo build --release --target $i.triple --features custom-protocol
if ($LASTEXITCODE -ne 0) { Pop-Location; throw "cargo 构建失败" }

# 版本号：Android 工程读的是 app/tauri.properties（正常由 cargo tauri android build 生成，
# 但本脚本走「手工 copy + gradle」，所以要自己同步，否则 apk 里还是旧版本号）。
$conf = Get-Content "$root\src-tauri\tauri.conf.json" -Raw -Encoding UTF8 | ConvertFrom-Json
$ver = $conf.version
$code = 0
foreach ($seg in ($ver -split '\.')) { $code = $code * 1000 + [int]$seg }
$props = "$root\src-tauri\gen\android\app\tauri.properties"
@"
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
tauri.android.versionName=$ver
tauri.android.versionCode=$code
"@ | Set-Content -Path $props -Encoding UTF8
Write-Host "   版本 $ver（versionCode $code）已写入 tauri.properties" -ForegroundColor DarkGray
$so = "target\$($i.triple)\release\liblab_assistant_lib.so"
$dst = "gen\android\app\src\main\jniLibs\$Abi"
New-Item -ItemType Directory -Force -Path $dst | Out-Null
Copy-Item $so "$dst\liblab_assistant_lib.so" -Force
Write-Host "   已拷入 $dst" -ForegroundColor DarkGray

# 自检：单文件 HTML 是**编译期**内嵌进 .so 的，如果 .so 比 HTML 旧，就会打包出陈旧前端。
# 这里用「HTML 里的一段特征串」验证 .so 确实是按当前 HTML 编出来的。
# 页面文件名改过几轮（原型.html / 实验助手v0.1beta.html），按候选名 + mtime 兜底解析。
$htmlFile = $null
foreach ($n in @("原型.html", "实验助手.html", "实验助手v0.2beta.html", "实验助手v0.1beta.html")) {
  $p = Join-Path $root $n
  if (Test-Path $p) { $htmlFile = $p; break }
}
if (-not $htmlFile) {
  $htmlFile = Get-ChildItem $root -Filter *.html |
    Where-Object { $_.Name -like "实验助手*" -or $_.Name -like "原型*" } |
    Sort-Object LastWriteTime -Descending | Select-Object -First 1 -ExpandProperty FullName
}
if (-not $htmlFile) { throw "找不到单文件页面（原型.html / 实验助手*.html），无法做内嵌前端自检" }
Write-Host "   前端真源：$(Split-Path $htmlFile -Leaf)" -ForegroundColor DarkGray
$html = Get-Content $htmlFile -Raw -Encoding UTF8
$marker = '<details class="card card-fold">'
if ($html.Contains($marker)) {
  $bytes = [System.IO.File]::ReadAllBytes((Join-Path (Get-Location) $so))
  $needle = [System.Text.Encoding]::UTF8.GetBytes($marker)
  $found = $false
  for ($k = 0; $k -le $bytes.Length - $needle.Length; $k++) {
    if ($bytes[$k] -eq $needle[0]) {
      $ok = $true
      for ($j = 1; $j -lt $needle.Length; $j++) { if ($bytes[$k + $j] -ne $needle[$j]) { $ok = $false; break } }
      if ($ok) { $found = $true; break }
    }
  }
  if (-not $found) {
    Pop-Location
    throw "内嵌页面不是最新的：.so 里没有当前 HTML 的特征串。请先确认 cargo 真的重新编译了（改过 HTML 后必须重编）。"
  }
  Write-Host "   自检通过：.so 内嵌的前端与当前 HTML 一致" -ForegroundColor DarkGray
}
Pop-Location

Write-Host "3/4 Gradle 打包 ..." -ForegroundColor Cyan
Push-Location "$root\src-tauri\gen\android"
$variant = if ($Debug) { "Debug" } else { "Release" }
# rust 插件生成的任务名 = "rustBuild" + <arch 首字母大写> + <Profile>
# （x86_64 → rustBuildX86_64Release，不是 rustBuildx86_64Release）。
$taskArch = $i.arch.Substring(0, 1).ToUpper() + $i.arch.Substring(1)
& $GradleBin --no-daemon `
  "-PabiList=$Abi" "-ParchList=$($i.arch)" "-PtargetList=$($i.target)" `
  ":app:assemble$($i.flavor)$variant" `
  "-x" "rustBuild$taskArch$variant" "-x" "rustBuildUniversal$variant"
if ($LASTEXITCODE -ne 0) { Pop-Location; throw "gradle 打包失败" }
Pop-Location

$apkDir = "$root\src-tauri\gen\android\app\build\outputs\apk\universal\$($variant.ToLower())"
$apk = Get-ChildItem $apkDir -Filter *.apk | Sort-Object LastWriteTime -Descending | Select-Object -First 1
if (-not $apk) { throw "没找到 apk（$apkDir）" }

$outDir = "$root\build"
New-Item -ItemType Directory -Force -Path $outDir | Out-Null
$name = "实验助手-v$ver-$Abi-$(if ($Debug) { 'debug' } else { 'release' }).apk"
$out = "$outDir\$name"

if ($Debug) {
  Copy-Item $apk.FullName $out -Force
} else {
  Write-Host "4/4 签名 ..." -ForegroundColor Cyan
  $ks = "$outDir\lab-debug.jks"
  if (-not (Test-Path $ks)) { throw "缺少签名用的 keystore：$ks（可用 keytool 生成，或改跑 -Debug）" }
  & "$env:ANDROID_HOME\build-tools\35.0.0\apksigner.bat" sign `
    --ks $ks --ks-pass pass:android --key-pass pass:android --ks-key-alias labdebug `
    --out $out $apk.FullName
  if ($LASTEXITCODE -ne 0) { throw "签名失败" }
}

$mb = [math]::Round((Get-Item $out).Length / 1MB, 2)
Write-Host "`n✅ 出炉：$out  ($mb MB)" -ForegroundColor Green
Write-Host "   安装：adb install -r `"$out`"" -ForegroundColor Green
